services:
  source-of-voice-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${FE_CONTAINER:-source-of-voice-fe}"
    ports:
      - "${HOST_PORT:-8000}:${CONTAINER_PORT:-80}"
    environment:
      API_BASE_URL: ""
      API_GATEWAY_URL: "${API_GATEWAY_URL:-http://api-gateway:8080}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT}", "&&",
              "curl", "-f", "http://localhost:${CONTAINER_PORT}/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s