name: frontend-ci.yml
on:
  [ push ]
jobs:
  Linter:
    name: Check formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker linter
        run: docker build -f Dockerfile.linter -t linter .

      - name: Run linter
        run: docker run --rm -v ${{ github.workspace }}:/app linter




